// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAosWsjiZF46YUeVcsiC33M_leI2-1S5Dc',
    appId: '1:819525906495:web:d788694667bee6185dc88a',
    messagingSenderId: '819525906495',
    projectId: 'budget-fb399',
    authDomain: 'budget-fb399.firebaseapp.com',
    storageBucket: 'budget-fb399.appspot.com',
    measurementId: 'G-LKEKVB4G4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Ot2GpKX38kJXgi23tJas42lsejKYE14',
    appId: '1:819525906495:android:158d9d6b6de1f2e15dc88a',
    messagingSenderId: '819525906495',
    projectId: 'budget-fb399',
    storageBucket: 'budget-fb399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLVEAo9BNlaY3jS2QIcFp-DQs6iLUiQY',
    appId: '1:819525906495:ios:2803f51a82da2d395dc88a',
    messagingSenderId: '819525906495',
    projectId: 'budget-fb399',
    storageBucket: 'budget-fb399.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLVEAo9BNlaY3jS2QIcFp-DQs6iLUiQY',
    appId: '1:819525906495:ios:368826492e5ac7c15dc88a',
    messagingSenderId: '819525906495',
    projectId: 'budget-fb399',
    storageBucket: 'budget-fb399.appspot.com',
    iosBundleId: 'com.example.myProject.RunnerTests',
  );
}
